name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: sh /home/runner/work/G1_8bit_MCUs_Drivers/G1_8bit_MCUs_Drivers/.github/workflows/configure.sh
    - name: Building C Version
      run: make build -C C
    - name: Clean
      run: sh /home/runner/work/G1_8bit_MCUs_Drivers/G1_8bit_MCUs_Drivers/.github/workflows/clean.sh 
  
  style-checking:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Setup vera 
        run: sh /home/runner/work/G1_8bit_MCUs_Drivers/G1_8bit_MCUs_Drivers/.github/workflows/setupVera.sh
      - name: Style-Checking
        run: make style-check -C C
      - name: Clean
        run: sudo apt remove vera++