name: RUNNING CI [BUILD AND TEST] 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup vera 
      run: sh /home/runner/work/G1_8bit_MCUs_Drivers/G1_8bit_MCUs_Drivers/.github/workflows/setupVera.sh
    - name: Style-Checking
      run: make style-check -C C
    - name: Clean
      run: sudo apt remove vera++

  build:
    runs-on: ubuntu-latest
    needs: [style-checking]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Build
      run: sh /home/runner/work/G1_8bit_MCUs_Drivers/G1_8bit_MCUs_Drivers/.github/workflows/configure.sh
    - name: Building C Version
      run: make build -C C
    # - name: Clean
    #   run: sh /home/runner/work/G1_8bit_MCUs_Drivers/G1_8bit_MCUs_Drivers/.github/workflows/clean.sh 
  
  regression-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Tests
      run: sh /home/runner/work/G1_8bit_MCUs_Drivers/G1_8bit_MCUs_Drivers/.github/workflows/configure-test.sh
    - name: Testing For C Version
      run: make run-regressions filter=all -C C 
    - name: Clean
      run: sh /home/runner/work/G1_8bit_MCUs_Drivers/G1_8bit_MCUs_Drivers/.github/workflows/clean.sh
    - name: Clean
      run: sh /home/runner/work/G1_8bit_MCUs_Drivers/G1_8bit_MCUs_Drivers/.github/workflows/clean-test.sh 